ALTER TABLE users
ADD COLUMN IF NOT EXISTS email VARCHAR(255);

UPDATE users
SET email = username
WHERE email IS NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
